baseURL = 'https://weckhorst.no/'
languageCode = 'en-us'
title = 'Hello There'
theme = 'hello-friend-ng'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  dateform		= "Jan 2, 2006"
  dateformShort		= "Jan 2"
  dateformNum		= "02.01.2006"
  dateformNumTime	= "02.01.2006 15:04"

  homeSubtitle		= "Nothing to see here..."

  disableReadOtherPosts = false
  enableSharingButtons	= false
  enableGlobalLanguageMenu = false

  description = "Hello There"

